apiVersion: v2
name: k8s-bootstrap-applications
description: K8S Boostrap Applications
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 1.0.0