apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-autoscaler
    name: in-cluster
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    targetRevision: 9.35.0
    path: chart
    helm:
      valueFiles:
        - values/cluster-autoscaler/values.yaml

