{{- if .Values.clusterAutoscaler.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: cluster-autoscaler
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/autoscaler
      chart: cluster-autoscaler
      targetRevision: {{ .Values.clusterAutoscaler.spec.sources.helm.targetRevision }}
      helm:
        valueFiles:
          - $valuesSrc/values/cluster-autoscaler/values.yaml
    - repoURL: 'https://github.com/ohlen1/k8s-argo-bootstrap'
      targetRevision: {{ .Values.clusterAutoscaler.spec.sources.values.targetRevision }}
      ref: valuesSrc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
{{- end }}
