{{- if .Values.ingressNginx.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://kubernetes.github.io/ingress-nginx
      chart: ingress-nginx
      targetRevision: {{ .Values.ingressNginx.spec.sources.helm.targetRevision }}
      helm:
        valueFiles:
          - $valuesSrc/values/ingress-nginx/values.yaml
    - repoURL: 'https://github.com/ohlen1/k8s-argo-bootstrap'
      targetRevision: {{ .Values.ingressNginx.spec.sources.values.targetRevision }}
      ref: valuesSrc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
{{- end }}

