{{- if .Values.prometheusStack.enabled -}}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-stack
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: prometheus-stack
    server: https://kubernetes.default.svc
  project: default
  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: {{ .Values.prometheusStack.spec.sources.helm.targetRevision }}
      helm:
        valueFiles:
          - $valuesSrc/values/prometheus-stack/values.yaml
    - repoURL: 'https://github.com/ohlen1/k8s-argo-bootstrap'
      targetRevision: {{ .Values.prometheusStack.spec.sources.values.targetRevision }}
      ref: valuesSrc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # https://foxutech.medium.com/how-to-fix-too-long-must-have-at-most-262144-bytes-in-argocd-2a00cddbbe99
{{- end }}

