prometheus-node-exporter:
  prometheus:
    monitor:
      enabled: true

prometheus:
  enabled: true
  prometheusSpec:
    replicas: 1
  podMetadata:
    labels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: prometheus-stack
  ingress:
    enabled: false

grafana:
  enabled: true
  plugins:
    - grafana-worldmap-panel
    - grafana-clock-panel
    - natel-plotly-panel
    - yesoreyeram-boomtable-panel
    - snuids-radar-panel
    - camptocamp-prometheus-alertmanager-datasource
    - grafana-piechart-panel
  podLabels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: prometheus-stack
  ingress:
    enabled: false



